#!/bin/bash

# Fish PPA (if not already added)
grep -q "^deb .*fish-shell/release-3" /etc/apt/sources.list /etc/apt/sources.list.d/* || sudo apt-add-repository ppa:fish-shell/release-3 -y

# Green coloured message
echo -e "\e[32mUpdating package list and installing Fish and Nala if not already installed...\e[0m"

# Install fish and nala (if not already installed)
if ! command -v fish &> /dev/null; then
    sudo apt-get update
    sudo apt-get install fish -y
fi

if ! command -v nala &> /dev/null; then
    sudo apt-get update
    sudo apt-get install nala -y
fi

# Check if WSLg or GUI support is available
if [ ! -z "$DISPLAY" ]; then
    fish .config/yadm/bootstrap.fish
else
    # Coloured Error message
    echo -e "\e[31mWSLg or GUI support is not available. Please enable it to continue the setup\e[0m"
fi
